### ISSUE TITLE
crash with Grav 1.7.12

### ISSUE THREAD

**Issue by securiteinfo** [OrthoCube/grav-plugin-tag-manager#2]
PHP Fatal error:  require(): Failed opening required '<my_path>/user/plugins/tag-manager/vendor/autoload.php' (include_path='.:/usr/share/php') in <my_path>/user/plugins/tag-manager/tag-manager.php on line 44

Real path has been anonymized using <my_path>.

**Comment by skinofthesoul** [comment]
I just had the same issue. Will this be fixed at some point? I think the plugin is very useful!

**Comment by BullyH** [comment]
Same here ... the whole site crashes! - Please update the plug-in.
